### ISSUE TITLE
threading

### ISSUE THREAD

**Issue by c-cube** [UnixJunkie/dolog#10]
Wouldn't it be useful, in multi-threaded programs (or even just programs compiled with -thread), to have the logger run in a separate thread? In case the out_channel is slow (network, FS...), that wouldn't make the main thread block for maybe hundreds of milliseconds just for a call to Log. What's your opinion?

**Comment by UnixJunkie** [comment]
Also, if the logs were not synchronous with the program, it would
make debugging based on execution traces/logs much harder or even impossible
