### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by cdisselkoen** [UnixJunkie/dolog#26]
I didn't see a LICENSE file - what license are the Releases released under?  (MIT? BSD? GPL?)  Could we add a LICENSE file?

**Comment by UnixJunkie** [comment]
```bash
# opam info dolog | grep license
license:      "BSD-3-Clause"
```

**Comment by UnixJunkie** [comment]
Yes, a license file should be added to the repository.

**Comment by UnixJunkie** [comment]
done
